name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/fastapi-book-project &&
            git pull &&
            sudo apt update && sudo apt install python3 python3-venv -y &&
            python3 -m venv venv &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            pkill -f uvicorn || true && 
            nohup venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &