name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/fastapi-book-project &&
            git pull &&
            sudo apt update && sudo apt install python3 python3-venv -y &&
            source venv/bin/activate || python3 -m venv venv && source venv/bin/activate &&
            pip install --upgrade pip &&
            pip install -r requirements.txt &&
            sudo systemctl restart fastapi
            